spring.application.name=api-gateway
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

## Product Service Route
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/product/**

## Category Service Route
spring.cloud.gateway.server.webflux.routes[1].id=category-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://category-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/categories/**


## Discovery Service Route
spring.cloud.gateway.server.webflux.routes[2].id=discovery-server
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/eureka/web
spring.cloud.gateway.server.webflux.routes[2].filters[0]=SetPath=/


## Discovery Service static Route
spring.cloud.gateway.server.webflux.routes[3].id=discovery-server-static
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/eureka/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/