import {
  PiArrowArcLeft,
  PiArrowLeftBold,
  PiArrowLineUpRightBold,
  PiBellDuotone,
  PiCameraBold,
  PiCertificateFill,
  PiChatDuotone,
  PiCheckCircleFill,
  PiDotsThreeBold,
  PiDotsThreeVerticalBold,
  PiEyeDuotone,
  PiEyeSlash,
  PiFileFill,
  PiFunnelDuotone,
  PiGearDuotone,
  PiGearFine,
  PiGraphDuotone,
  PiHouseBold,
  PiHouseDuotone,
  PiImageDuotone,
  PiLightbulbFilamentFill,
  PiListChecksBold,
  PiMagnifyingGlassDuotone,
  PiMapPinAreaDuotone,
  PiMapPinFill,
  PiMapPinSimple,
  PiMicrophoneLight,
  PiMoonStarsBold,
  PiPencilSimpleSlashBold,
  PiPlusBold,
  PiQrCodeBold,
  PiRecycleBold,
  PiScanBold,
  PiScanDuotone,
  PiSignOutBold,
  PiSpinnerBold,
  PiSuitcaseSimpleBold,
  PiSunBold,
  PiTrashDuotone,
  PiTrashSimpleDuotone,
  PiTrayDuotone,
  PiUploadDuotone,
  PiUserCircleFill,
  PiWarningFill,
  PiWheelchairDuotone,
  PiWindmill,
} from "react-icons/pi";

export const Icons = {
  pin: PiMapPinSimple,
  renewable: PiWindmill,
  clustered: PiGraphDuotone,
  disability: PiWheelchairDuotone,
  check: PiCheckCircleFill,
  logout: PiSignOutBold,
  warn: PiWarningFill,
  view: PiEyeDuotone,
  filter: PiFunnelDuotone,
  empty: PiTrayDuotone,
  home: PiHouseDuotone,
  address: PiMapPinAreaDuotone,
  location: PiMapPinFill,
  add: PiPlusBold,
  search: PiMagnifyingGlassDuotone,
  image: PiImageDuotone,
  upload: PiUploadDuotone,
  trash: PiTrashDuotone,
  scan: PiScanDuotone,
  spinner: PiSpinnerBold,
  bell: PiBellDuotone,
  user: PiUserCircleFill,
  mic: PiMicrophoneLight,
  camera: PiCameraBold,
  back: PiArrowLeftBold,
  delete: PiTrashSimpleDuotone,
  menu: PiDotsThreeBold,
  certificate: PiCertificateFill,
  edit: PiPencilSimpleSlashBold,
  gear: PiGearDuotone,
  threedot_menu: PiDotsThreeVerticalBold,
  message: PiChatDuotone,
  file: PiFileFill,
  moon: PiMoonStarsBold,
  sun: PiSunBold,
  scanner: PiScanBold,
  rotateLeft: PiArrowArcLeft,
  qrcode: PiQrCodeBold,
  employed: PiSuitcaseSimpleBold,
  reorganized: PiRecycleBold,
  growth: PiArrowLineUpRightBold,
  shade: PiHouseBold,
  eye_slash: PiEyeSlash,
  check_list: PiListChecksBold,
  gear_fine: PiGearFine,
  policy: PiFileFill,
  bulb: PiLightbulbFilamentFill,
};
