spring.application.name=api-gateway
server.port=8181
spring.address=0.0.0.0
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka

logging.level.root=INFO
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE

## Product Service Route
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/product/**, /swagger-ui.html, /swagger-ui/**, /v3/api-docs/**, /v3/api-docs

## User Service Route
spring.cloud.gateway.server.webflux.routes[4].id=user-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/users/**

## Category Service Route
spring.cloud.gateway.server.webflux.routes[1].id=category-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://category-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/categories/**


## Discovery Service Route
spring.cloud.gateway.server.webflux.routes[2].id=discovery-server
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/eureka/web
spring.cloud.gateway.server.webflux.routes[2].filters[0]=SetPath=/


## Discovery Service static Route
spring.cloud.gateway.server.webflux.routes[3].id=discovery-server-static
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8761
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/eureka/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=SetPath=/


## Product search Service static Route
spring.cloud.gateway.server.webflux.routes[5].id=product-search-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://product-search-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/products/**

spring.cloud.gateway.server.webflux.routes[6].id=recommendation-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8000
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/recommendations/**


# Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ecommerce